### ISSUE TITLE
How to manually trigger?

### ISSUE THREAD

**Issue by jshster** [lloiser/jquery-searcher#3]
Hi there,
Not sure if I'm doing this the right way but I love this class but can't seem to manually trigger the searcher functionality.  I basically have other filters on the page. While I have successfully used the toggle method to assess those filters before showing or hiding data I can't get it working the other way.  Essentially what I need to do is to say if the user clicks on one of the other filters and there is a value in the searcher field then trigger the searcher functionality.

I've tried using trigger('change') and trigger('keyup') neither of which do anything.

Any advise would be appreciated.

**Comment by lloiser** [comment]
The problem is most likely this line:
https://github.com/lloiser/jquery-searcher/blob/master/src/jquery.searcher.js#L72
I'm avoiding multiple `toggle` calls by comparing the actual input value and the last input value.

can you provide an example using jsfiddle or jsbin? maybe we can find another solution..

**Comment by idleberg** [comment]
I was about to ask the same. I'm using keyboard shortcuts to clear the search input, e.g. first <kbd>Esc</kbd> clears the input (and the table is stuck at the last filtered state), the second <kbd>Esc</kbd> blurs the input.

**Comment by lloiser** [comment]
I have added a public method "filter" which can be used to manually update the current filter.

``` js
$myTable.searcher("filter", "<myFilterValue>");
```

**Comment by idleberg** [comment]
Great, thank you!
