### ISSUE TITLE
Add reset button

### ISSUE THREAD

**Issue by ezersky** [lloiser/jquery-searcher#6]
Sorry for question.

How add reset button functionality to plugin?

1. Display all results
2. Type word and display results by typed word
4. Click «reset» and display all results

**Comment by lloiser** [comment]
Add a button and add a `click` listener to it that calls:
```js
$(<inputSelector>).val("").trigger("change")
```
(replace `<inputSelector>` with the selector you already passed to this plugin)

**Comment by ezersky** [comment]
Thanks a lot!
